import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/Navbar";
import { dbConnect } from "@/services/db";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="py-8">
          <AuthProvider>{children}</AuthProvider>
        </main>
        <ToastContainer
          position="top-right"
          theme="dark"
        ></ToastContainer>
      </body>
    </html>
  );
}
